### PR TITLE
Refactor for readability

### PR DESCRIPTION
**Pull request by jaimeiniesta**
This PR is for a general refactor of the code, trying to achieve more readability of the code, by:

* Defining an `Environment` defstruct. This allows to create custom environments like:

```elixir
%Environment{base_url: "https://example.com"}
```
* Defining a `Credentials` defstruct to hold together `client_id` and `client_secret` instead of passing them as separate arguments.

* Using pattern matching on those structs on the function definitions to ensure the correct struct is passed and simplify readability.

* Simplify calls, using `get` and `post` instead of `perform_get` and `perform_post`.

Also, not included in this PR, but I suggest removing the `infrastructure` directory and moving all the modules to the top level. If everything is infrastructure, why having this directory and longer names?

Instead of

```elixir
StuartClientElixir.Infrastructure.Authenticator
StuartClientElixir.Infrastructure.Credentials
StuartClientElixir.Infrastructure.Environment
StuartClientElixir.Infrastructure.HttpClient
StuartClientElixir.Infrastructure.Queue
```

we could just have

```elixir
StuartClientElixir.Authenticator
StuartClientElixir.Credentials
StuartClientElixir.Environment
StuartClientElixir.HttpClient
StuartClientElixir.Queue
```

### CODE REVIEW

**Comment by jaimeiniesta** [comment]
Thanks @seanhandley 

I just removed the `Infrastructure` namespace and defined `get` and `post` at the top level.

**Comment by maximilientyc** [comment]
Oh I saw you PR too late apparently... 

FYI within the team we maintain the PHP, Ruby, Java, Elixir and JS library, that's why we tried to design all of these the same way 😬: `perform_*`, infrastructure package, etc. This is to facilitate maintainability on our end.

The `Infrastructure` package is useless for now, but at some point it's going to be required when adding business methods. More details in the [php library](https://github.com/StuartApp/stuart-client-php/tree/master/src/Stuart) which is more evolved.

**Comment by maximilientyc** [comment]
Additionally, once merged to master we are going to need to increase the version number to `1.2.0`, and then re-publish to hex. I will take care of it.

**Comment by jaimeiniesta** [comment]
Thanks for the explanation! We can bring back the `Infrastructure` namespace when it's needed.

Regarding `perform_*`, my motivation was making it more similar to other Elixir libraries like HTTPoison.

For the release, there's no need to do it now, we can wait for other upcoming features / fixes if you wish.

**Pull request merged**
